version: '3.8'  # Adding version explicitly

services:
  db:
    image: mysql:8.0
    platform: linux/amd64  # Add this for M1/M2 Macs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dicom_db
      MYSQL_USER: dicom_user
      MYSQL_PASSWORD: dicom_password
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=dicom_db
      - DB_USER=dicom_user
      - DB_PASS=dicom_password
    volumes:
      - type: volume
        source: dicom-files
        target: /app/dicom_files
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

# Define volumes explicitly
volumes:
  mysql-data:
    name: mysql-data
  dicom-files:
    name: dicom-files

# Define network explicitly
networks:
  app-network:
    name: app-network
    driver: bridge